### ISSUE TITLE
Move project to https://github.com/argoproj-labs

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argo-java-client#1]
Hello @unikzforce! Thank you for creating Java library for Workflows.

Please consider moving it to  https://github.com/argoproj-labs . The `argoproj-labs` was created to host argo related repositories to increase visibility and attract contributors.

**Comment by unikzforce** [comment]
hello @alexmt ! Thanks for your attention. how should i transfer this project to there? I'm willing to do that.

**Comment by alexmt** [comment]
Awesome, thank you! I've sent you an invitation to the org. Once you accept it you should be able to transfer the repo. Please add also add OWNERS file as described here https://github.com/argoproj-labs/community

**Comment by unikzforce** [comment]
I did it captain. Thanks for your support. I'll try to create OWNERS file and also update the models ASAP.

**Comment by unikzforce** [comment]
OWNERS file is added.
