### ISSUE TITLE
WorkflowStatus:  NodeStatus needs to be an argo object 

### ISSUE THREAD

**Issue by GAHila** [argoproj-labs/argo-java-client#3]
In WorkflowStatus - definition of which is missing from openspec, the nodes map is specified as 

	private Map<String, V1NodeStatus> nodes = new HashMap<String, V1NodeStatus>();

where V1NodeStatus is: io.kubernetes.client.models.V1NodeStatus;

However I think, NodeStatus needs to be another object of Argo rather than kubernetes according to:

https://github.com/argoproj/argo/blob/v2.3.0/pkg/apis/workflow/v1alpha1/types.go#L526

**Comment by unikzforce** [comment]
Sorry for my very late response, the WorkflowStatus has been officially added to the OpenApi json inside the Main Argo project, so I'll re-generate based on that

**Comment by unikzforce** [comment]
Yes , You are completely Right, I'll fix it to night or tommorow
