### ISSUE TITLE
Deploy To Github Packages

### ISSUE THREAD

**Issue by unikzforce** [argoproj-labs/argo-java-client#8]
@alexmt @alexec  Hey there guys, I wanted to publish a jar artifact to the Github Packages with this piece of code:

![image](https://user-images.githubusercontent.com/7010566/73615835-0c277900-4621-11ea-9414-81097f29b3a9.png)

I thought that It's better to tie this maven artifact to the this Repository and this Organization.
But Unfortunately I don't have Enough Privileges to do this:

![image](https://user-images.githubusercontent.com/7010566/73615869-67596b80-4621-11ea-8220-a0f473cfce21.png)

 Can any of you guys provide me the privilege of uploading artifact to this repo?

**Comment by unikzforce** [comment]
And please do not Ignore my requests, I'm trying to do a positive endeavor here.

**Comment by alexec** [comment]
To avoid getting off on the wrong food - I don't think we ever intentionally ignore requests - but we do get busy. 

AFAIK we don't publish anything to Github repository - but I'm interested because the Java client we'll be developing for the Argo Server API will probably need to. 

@alexmt is this something you've done?

Alex

**Comment by alexec** [comment]
While I remember, can I invite you to join the #argo-sdk Slack channel? As part of Argo v2.7 we plan to provide SDKs in a number of languages including Java and Python. I think this would be something you'd find really interesting and could bring a great deal of value too as port of a working group.

**Comment by unikzforce** [comment]
@alexec My mistake, Thank you
And sure, I would really love to join the effort on the slack working group. 
Anyway i was reading the issue that you have mentioned here. The plan for GRPC is fantastic, and i think it would eventually make a REST client like this irelevant then.

**Comment by alexec** [comment]
> And sure, I would really love to join the effort on the slack working group.

The channel is named: #argo-sdks - when you join it'd be good to say hi and let people know what you're doing.

**Comment by unikzforce** [comment]
Sure, After my deadline for today I'll try to join the channel.

**Comment by unikzforce** [comment]
@alexec I doubt that I can join by myself. The argo slack join link is not working:
![image](https://user-images.githubusercontent.com/7010566/74069752-66a34980-4a14-11ea-8729-9d9fddcaff69.png)

![image](https://user-images.githubusercontent.com/7010566/74069774-70c54800-4a14-11ea-8805-cb396878ad6b.png)

**Comment by unikzforce** [comment]
I was able to join the link there
