### ISSUE TITLE
v2.5 Client

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-java-client#9]
@unikzforce - as I think you know, I'm currently building tooling to generate Java and Python clients for the classic/legacy kube API and the  ew server API.

It'd be great get you involved in this. Would this be something you'd be interested in?

**Comment by unikzforce** [comment]
@alexec sure, Yes I would love to.
Now the Argo Slack workspace joining link is working fine. I was able to join the workspace.
Now I think I would need your Advice and Guidance to follow the next steps.
